spring:
  application:
    name: practica3  # Nombre de la aplicación

  datasource:
    url: jdbc:h2:file:./data/usuarios
    username: admin
    password: admin
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true  # Habilita la consola de H2 en http://localhost:8080/h2-console
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false  # Evita accesos remotos a la consola de H2

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true  # Muestra las consultas SQL en consola
    hibernate:
      ddl-auto: update  # Mantiene la estructura de la BD sin borrar datos

logging:
  level:
    root: ERROR
    org.hibernate.SQL: DEBUG  # Muestra las consultas SQL
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Muestra los valores de los parámetros en las consultas